<h1 class="text-title">TỈ GIÁ TIỀN TỆ</h1>
<table style="width:100%">
  <tr class="first-row">
    <th>TÊN NGOẠI TỆ</th>
    <th>MÃ NGOẠI TỆ</th>
    <th>TIỀN MẶT</th>
    <th>CHUYỂN KHOẢN</th>
    <th>BÁN</th>
  </tr>
<?php
    $url = "https://portal.vietcombank.com.vn/Usercontrols/TVPortal.TyGia/pXML.aspx?b=68";
    $feeds = simplexml_load_file($url);

    $i=0;
    if(!empty($feeds)){
        $extraList = $feeds->Exrate;
        foreach ($extraList as $item) {
            echo '
                <tr>
                    <th>' . $item['CurrencyName'] .'</th>
                    <th>' . $item['CurrencyCode'] .'</th>
                    <th>' . $item['Buy'] .'</th>
                    <th>' . $item['Transfer'] .'</th>
                    <th>' . $item['Sell'] .'</th>
                </tr>
            ';
        }
    }
?>
</table>

<style>
@import url('https://fonts.googleapis.com/css2?family=Bungee+Inline&family=Kanit&family=Oswald&family=VT323&family=Roboto+Condensed&display=swap');
.navigation{
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
}
.navigation a{
    text-decoration: none;
    color: #070404;
    font-family: 'Roboto Condensed';
    letter-spacing: 1px;
    transition: 0.2s;
    font-size: 19px;
}

.footer,.copyright{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 0.5px;
}
.block-title{
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
  text-transform: uppercase;
}

.block-title strong{
    font-size: 40px !important;
}

.header{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    color: white;
}
.header a{
    font-size: 17px !important;
}
.header span{
    font-size: 17px !important;
}
.header .authorization-link{
    font-size: 17px !important;
}

#search{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    font-size: 16px !important;
}

.text-title{
  margin-top: 10px;
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
}


</style>