<?php
/** @var \Custom\Weather\Block\WeatherBlock $block */
?>
<?php
    $isData = false;
    $name = '';
    if(!empty($_GET) && !empty($_GET['city'])) {
        $name = $_GET['city'];
        $result = $block->getWeatherInformation($_GET['city']);
        if ($result->cod == '200') {
            $main = $result->weather[0]['main'];
            $description = $result->weather[0]['description'];
            $icon = $result->weather[0]['icon'];
            $temp = $result->main['temp'] - 273.15;
            $temp_min = $result->main['temp_min'];
            $temp_max = $result->main['temp_max'];
            $umid = $result->main['humidity'];
            $isData = true;
        }
    }
?>

<style>
@import url('https://fonts.googleapis.com/css2?family=Bungee+Inline&family=Kanit&family=Oswald&family=VT323&family=Roboto+Condensed&display=swap');
.navigation{
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
}
.navigation a{
    text-decoration: none;
    color: #070404;
    font-family: 'Roboto Condensed';
    letter-spacing: 1px;
    transition: 0.2s;
    font-size: 19px;
}

.footer,.copyright{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 0.5px;
}
.block-title{
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
  text-transform: uppercase;
}

.block-title strong{
    font-size: 40px !important;
}

.header{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    color: white;
}
.header a{
    font-size: 17px !important;
}
.header span{
    font-size: 17px !important;
}
.header .authorization-link{
    font-size: 17px !important;
}

#search{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    font-size: 16px !important;
}

.text-title{
  margin-top: 10px;
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
}

#show_weather{
    font-family: 'Roboto Condensed';
    letter-spacing: 1px;
}
.page-footer{
    margin-top: 30px !important;
}
.title{
    font-weight: bold;
    font-size: 30px;
    text-align: center;
    color: white;
}
</style>
<h1 class="text-title">DỰ BÁO THỜI TIẾT</h1>
<div id="show_weather">
    <form class="search-weather" action="/weather/" method="GET">
        <input type="text" placeholder="Nhập tên thành phố" id="search-txt" name="city" value="<?php echo $name ?>">
        <button button type="submit" id="weather_button">Xem thời tiết</button> </br>
        <?php if($name != '' && !$isData) echo '<i class="text_danger">Không tìm thấy dữ liệu</i>' ?>
    </form>

    <div class="city-icon">
        <div class="city-icon-holder">
        <div id="city-name"><?php if($isData) echo $name ?></div>
        <img src="<?php if($isData) echo 'http://openweathermap.org/img/w/' . $icon . '.png' ?>" alt="" id="icon">
        </div>
    </div>

    <div class="temperature">
       <div class="title">Nhiệt độ</div>
       <div id="temp"> <?php if($isData) echo $temp ?>°C</div>
    </div>

    <div class="humidity">
      <div class="title">Độ ẩm</div>
      <div id="humidity-div"> <?php if($isData) echo $umid ?>%</div>
    </div>
</div>
