<?php
    $url = "https://vnexpress.net/rss/kinh-doanh.rss";
    $feeds = simplexml_load_file($url);

    $i=0;
    if(!empty($feeds)){
    
    $site = $feeds->channel->title;
    $sitelink = $feeds->channel->link;

    echo"<h1 class='text-title'>BẢN TIN KINH DOANH</h1>";
    foreach ($feeds->channel->item as $item) {
      
    $title = $item->title;
    $link = $item->link;
    $description = $item->description;
    $postDate = $item->pubDate;
    $pubDate = date('D, d M Y',strtotime($postDate));


    if($i>=6) break;
?>
    <div class="post">
        <div class="post-head">
            <div class="post-title"><?php echo $title; ?></div>
            <div class="post-time"><?php echo $pubDate; ?></div>
        </div>
        <div class="post-content">
            <?php echo implode(' ', array_slice(explode(' ', $description), 0, 20)) . "..."; ?> <a class="post-link" href="<?php echo $link; ?>">Xem tiếp</a>
        </div>
    </div>

<?php
        $i++;
    }
    }else{
        if(!$invalidurl){
            echo "<h2>No item found</h2>";
        }
    }
?>

<style>
   
   @import url('https://fonts.googleapis.com/css2?family=Bungee+Inline&family=Kanit&family=Oswald&family=VT323&family=Roboto+Condensed&display=swap');

   .post{
       width: 33.33% !important;
       float: left !important;
       padding: 20px !important;
   }
   .post *{
    font-family: 'Roboto Condensed';
    letter-spacing: 0.5px;
   }

    .post-title{
        font-weight: bold;
        font-size: 19px;
        color: #252525;
    }

    .post-time{
        font-style: italic;
        margin: 3px 0px;
        color: #b95a1d;
    }

    .post-content{
        font-size: 16px;
    }

    .post-link{
        color: #006bb4 !important;
        font-weight: bold;
    }

   .navigation{
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
}
.navigation a{
    text-decoration: none;
    color: #070404;
    font-family: 'Roboto Condensed';
    letter-spacing: 1px;
    transition: 0.2s;
    font-size: 19px;
}

.footer,.copyright{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 0.5px;
}
.block-title{
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
  text-transform: uppercase;
}

.block-title strong{
    font-size: 40px !important;
}

.header{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    color: white;
}
.header a{
    font-size: 17px !important;
}
.header span{
    font-size: 17px !important;
}
.header .authorization-link{
    font-size: 17px !important;
}

#search{
    font-family: 'Roboto Condensed' !important;
    letter-spacing: 1px;
    font-size: 16px !important;
}

.text-title{
  margin-top: 10px;
  margin-bottom: 10px;
  text-align: center;
  font-family: Oswald;
  word-spacing: 3px;
  letter-spacing: 4px;
  color:  #070404;
  text-shadow: 0px 1px 4px white;
}

</style>

